config/routes.rb
Multistock::Application.routes.draw do

  match 'autocomplete/:action' => 'autocomplete'
  match 'inventur(/:action/:place)' => 'inventur' 

  resources :comments

  resources :place_types

  resources :places

  resources :devices

  root :to => 'devices#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :name, :text, :device_id
  
  belongs_to  :device
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html { redirect_to :controller => "devices", :action => "edit", :id => @comment.device.id}
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :controller => "devices", :action => "edit", :id => @comment.device.id }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to :controller => "devices", :action => "edit", :id => @comment.device.id}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to :controller => "devices", :action => "edit", :id => @comment.device.id}
        format.json { head :no_content }
      else
        format.html { redirect_to :controller => "devices", :action => "edit", :id => @comment.device.id}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    d_id = @comment.device.id
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to :controller => "devices", :action => "edit", :id => d_id}
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_for(Comment.new) do |f| %>
<table>
	<tr>
		<th style="text-align: left">Eigenschaften</th>
		<th style="text-align: left">Wert</th>
	</tr>
	<% @device.comment.each do |c| %>
	<tr>
		<td><%= c.name %>:</td>
		<td><%= c.text %></td>
		<td>
			<%= link_to "Edit", :controller => "comments", :action => "edit", :id => c.id%>
			<%= link_to "Destroy", {:controller => "comments", :id => c.id, :action => "show"}, {method: :delete, data: { confirm: 'Are you sure?' }} %>
		</td>
	</tr>
	<% end %>
	<tr>
		<td><%= f.text_field :name, :autofocus=>true, :class => "auto_search_complete", :id => "name" %></td>
  		<td><%= f.text_field :text, :id => "text" %></td>
    	<td>
    		<%= f.submit :value => "Hinzufügen"%>
    		<%= f.text_field :device_id, :value =>@device.id, :hidden => true%>
    	</td>
	</tr>
</table>
<% end %>

<lu id="list"></lu>

<script language="JavaScript">
	$('.auto_search_complete').autocomplete({
    //minLength: 2,
    delay: 600,
    source: function(request, response) {
        $.ajax({
            url: "/autocomplete/comments.json",
            dataType: "json",
            data: {term: request.term},
            success: function( data ) {
            	document.getElementById('list').innerHTML="";
            	for (var i = 0; i < data.length; i++)
	                document.getElementById('list').innerHTML= document.getElementById('list').innerHTML + 
	                "<li onclick='document.getElementById(\"name\").value=this.innerText; document.getElementById(\"list\").innerHTML=\"\"; document.getElementById(\"text\").focus();'>" + data[i].name + "</li>";
	            
            }
        });
    }           
});
</script>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_list.html.erb
<table>
	<tr>
		<th colspan="2" style="text-align: left">Eigenschaften</th>
	</tr>
	<% @device.comment.each do |c| %>
	<tr>
		<td><%= c.name %>:</td>
		<td><%= c.text %></td>
	</tr>
	<% end %>
</table>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', {:controller => "devices", :action => "edit", :id => @comment.device.id} %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>