config/routes.rb
Multistock::Application.routes.draw do

  match 'autocomplete/:action' => 'autocomplete'
  match 'inventur(/:action/:place)' => 'inventur' 

  resources :comments

  resources :place_types

  resources :places

  resources :devices

  root :to => 'devices#index'

end

app/models/device.rb
class Device < ActiveRecord::Base 
  attr_accessible :place_id
  
  belongs_to  :place
  
  has_many    :comment
  
  def self.valid_ean?(ean)
    ean = ean.to_s
    ean.length == 8 && ean == complete_ean(ean[0,7])
  end
  
  def self.complete_ean(seven)
    seven = seven.to_s
    return nil unless seven.length == 7 && seven.match(/\d{7}/)

    arr = (0..6).to_a.collect do |i|
      if (i+1) % 2 == 0
        seven[i,1].to_i
      else
        seven[i,1].to_i * 3
      end
    end
    sum = arr.inject { |sum, n| sum + n }
    remainder = sum % 10
    if remainder == 0
      check = 0
    else
      check = 10 - remainder
    end

    seven + check.to_s
  end
  
  def self.find_by_ean(ean)
    ean = ean.to_s
    return nil if not valid_ean?(ean)
    return self.find_by_id(ean[0,7])
  end
  
  def ean
    Device.complete_ean id
  end
  
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    
    if not params[:such].nil? and not params[:such][0][:name] == ""
      where = ""
      if params[:such_or]
        params[:such].each { |e|
          if not e[:name] == ''      
            if not where == ""
               where = where + ' OR '
            end
            where = where + "(name = '"+e[:name]+"' and text like '%"+e[:text]+"%')"
          end  
        }
        @devices = Device.find_by_sql "select devices.* from devices, (select device_id from comments where #{where} group by device_id) as comments where comments.device_id = devices.id"
      else
        i = 0
        from = "devices"
        params[:such].each { |e|
          if not e[:name] == ''      
            if not where == ""
               where = where + ' AND '
            end
            i = i + 1
            from = from + ", (select device_id as id from comments where name = '"+e[:name]+"' and text like '%"+e[:text]+"%') as c#{i}"
            where = where + "devices.id = c#{i}.id"
          end  
        }
        @devices = Device.find_by_sql "select devices.* from #{from} where #{where} group by devices.id"
      end
      
      @such = params[:such] 
    else
      @devices = Device.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])
    @place = @device.place

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to :controller => "devices", :action => "edit", :id => @device.id }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to :controller => "devices", :action => "edit", :id => @device.id }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<div style="float: left; width: 200px;">
<p>
  <b>Id:</b>
  <%= @device.ean %><br />
  <% @place= @device.place %>
  <% if @place.nil? %>
  	<br />
  	<b>Lagerort:</b><br />
  	unbekannt
  <% else %>
  	<%= render "places/show" %>
  <% end %>
  <br />
  
  
  Neuer Lagerort:<br />
  <input class="new_place" id="new_place"/> <br />		
  <lu id="plist"></lu>  
  <%= form_for(@device) do |f| %>
  		<%= f.text_field :place_id, :id => 'new_id', :hidden => true, :readonly => true %>
  		<%= f.submit :id => 'save' ,:value => "Speichern", :hidden => true %>
  <% end %>		
  
  

<script language="JavaScript">
$('.new_place').autocomplete({
    //minLength: 2,
    delay: 200,
    source: function(request, response) {
        $.ajax({
            url: "/autocomplete/places.json",
            dataType: "json",
            data: {term: request.term},
            success: function( data ) {
            	document.getElementById('plist').innerHTML="";
            	for (var i = 0; i < data.length; i++)
	                document.getElementById('plist').innerHTML= document.getElementById('plist').innerHTML + 
	                "<li onclick='document.getElementById(\"new_id\").value="+data[i].id+";document.getElementById(\"save\").hidden=false;"+
	                "document.getElementById(\"new_place\").disabled=true;document.getElementById(\"new_place\").value=this.innerText;document.getElementById(\"plist\").hidden=true;'>" + 
	                data[i].name + "</li>";
	            if (data.length == 0){
	            	document.getElementById('plist').innerHTML= '<%= link_to 'New Place', new_place_path %>';
	            }
            }
        });
    }           
});	
</script>
  
</p>
<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>
</div>




<%= render "comments/edit" %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<form method="get" id="such_form">
<table>
	<tr>
		<th>Name</th>
		<th>Wert</th>
	</tr>
	<% if not @such.nil?%>
		<% @such.each do |such| %>
		 <% if not such[:name] == ''%>
			<tr>
				<td><input name="such[][name]" value="<%= such[:name] %>" /></td>
				<td><input name="such[][text]" value="<%= such[:text] %>" /></td>
				<td><a href="#" onclick="$(this).parent().parent().remove(); document.getElementById('such_form').submit(); return false;">Remove</a></td>
			</tr>	
		 <% end %>
		<% end %>
	<% end %>
	<tr>
		<td><input name="such[][name]" autofocus="autofocus" class="auto_search_complete" /></td>
		<td><input name="such[][text]" /></td>
	</tr>
	
	<tr>
		<td><input type="checkbox" name="such_or" onclick="document.getElementById('such_form').submit();" <% if params[:such_or] %>checked="true"<%end%>/>Oder Suche</td>
		<td><input type="submit" value="Suchen" /></td>
	</tr>
</table>
</form>

<%= puts @params %>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Type</th>
    <th>Besitzer</th>
    <th>Lagerort</th>
    <th colspan="3"></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.ean %></td>
    <td><%= if device.comment.find_by_name(:name).nil?  then "-" else device.comment.find_by_name(:name).text  end %></td>
    <td><%= if device.comment.find_by_name(:type).nil?  then "-" else device.comment.find_by_name(:type).text  end %></td>
    <td><%= if device.comment.find_by_name(:owner).nil? then "-" else device.comment.find_by_name(:owner).text end %></td>
    <td><%= if device.place.nil?  then "-" else device.place.name end %></td>
    
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<div style="float: left; width: 200px;">
<p>
  <b>Id:</b>
  <%= @device.ean %>
  <br />
  <% if @place.nil? %>
  	<b>Lagerort:</b><br />
  	unbekannt
  <% else %>
  	<%= render "places/show" %>
  <% end %>
  <br />
  <%= link_to 'Edit', edit_device_path(@device) %> |
  <%= link_to 'Back', devices_path %>
</p>
</div>

<%= render "comments/list"%>