config/routes.rb
Multistock::Application.routes.draw do

  match 'autocomplete/:action' => 'autocomplete'
  match 'inventur(/:action/:place)' => 'inventur' 

  resources :comments

  resources :place_types

  resources :places

  resources :devices

  root :to => 'devices#index'

end

app/controllers/place_types_controller.rb
class PlaceTypesController < ApplicationController
  # GET /place_types
  # GET /place_types.json
  def index
    @place_types = PlaceType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @place_types }
    end
  end

  # GET /place_types/1
  # GET /place_types/1.json
  def show
    @place_type = PlaceType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place_type }
    end
  end

  # GET /place_types/new
  # GET /place_types/new.json
  def new
    @place_type = PlaceType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place_type }
    end
  end

  # GET /place_types/1/edit
  def edit
    @place_type = PlaceType.find(params[:id])
  end

  # POST /place_types
  # POST /place_types.json
  def create
    @place_type = PlaceType.new(params[:place_type])

    respond_to do |format|
      if @place_type.save
        format.html { redirect_to @place_type, notice: 'Place type was successfully created.' }
        format.json { render json: @place_type, status: :created, location: @place_type }
      else
        format.html { render action: "new" }
        format.json { render json: @place_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /place_types/1
  # PUT /place_types/1.json
  def update
    @place_type = PlaceType.find(params[:id])

    respond_to do |format|
      if @place_type.update_attributes(params[:place_type])
        format.html { redirect_to @place_type, notice: 'Place type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_types/1
  # DELETE /place_types/1.json
  def destroy
    @place_type = PlaceType.find(params[:id])
    @place_type.destroy

    respond_to do |format|
      format.html { redirect_to place_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/place_types_helper.rb
module PlaceTypesHelper
end

app/views/place_types/_form.html.erb
<%= form_for(@place_type) do |f| %>
  <% if @place_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_type.errors.count, "error") %> prohibited this place_type from being saved:</h2>

      <ul>
      <% @place_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/place_types/edit.html.erb
<h1>Editing place_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @place_type %> |
<%= link_to 'Back', place_types_path %>

app/views/place_types/index.html.erb
<h1>Listing place_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @place_types.each do |place_type| %>
  <tr>
    <td><%= place_type.name %></td>
    <td><%= link_to 'Show', place_type %></td>
    <td><%= link_to 'Edit', edit_place_type_path(place_type) %></td>
    <td><%= link_to 'Destroy', place_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place type', new_place_type_path %>

app/views/place_types/new.html.erb
<h1>New place_type</h1>

<%= render 'form' %>

<%= link_to 'Back', place_types_path %>

app/views/place_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @place_type.name %>
</p>


<%= link_to 'Edit', edit_place_type_path(@place_type) %> |
<%= link_to 'Back', place_types_path %>